language: node_js
node_js:
  - '7'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: a5a7611876512de3c8f75f8dd59687e8f2bd52647c85a72d93432bfd159e029f

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
